private/PROPOSAL/medium/Medium.cxx, private/PROPOSAL/medium/MediumFactory.cxx, public/PROPOSAL/medium/Medium.h, public/PROPOSAL/medium/MediumFactory.h
This is a new seawater implementation for Cascadia Basin, which is located in the Northeast Pacific Ocean at a depth of 2.66 km. Cascadia Basin is a potential site for future neutrino telescopes.
=> Implement Cascadia Basin seawater.

doc/Doxyfile.in
The documentation uses Unicode box-drawing characters not set up for use with LaTeX. Using the package pmboxdraw solves this problem.
=> Added extra package pmboxdraw to Doxyfile.in

private/PROPOSAL/Sector.cxx, private/PROPOSAL/scattering/Scattering.cxx, private/PROPOSAL/scattering/ScatteringHighland.cxx, private/PROPOSAL/scattering/ScatteringHighlandIntegral.cxx, private/PROPOSAL/scattering/ScatteringMoliere.cxx, private/PROPOSAL/scattering/ScatteringNoScattering.cxx, private/python/pybindings.cxx, private/python/scattering.cxx, public/PROPOSAL/scattering/Scattering.h, public/PROPOSAL/scattering/ScatteringHighland.h, public/PROPOSAL/scattering/ScatteringHighlandIntegral.h, public/PROPOSAL/scattering/ScatteringMoliere.h, public/PROPOSAL/scattering/ScatteringNoScattering.h, public/python/pyBindings.h, tests/Scattering_TEST.cxx
Scattering will now return a pair of averaged scattering direction
and the direction of the particle at the end of propagation step.
In "AdvanceParticle" scattering (direction change) and displacement will
from now on consider separately.
The testfile must be modified, since scattering no longer takes over
the displacement of the particle.
=> Avoid pulling random numbers at scattering when they are not needed.

private/Interface/python/particle.cxx, public/PROPOSAL/particle/ParticleDef.h
Singelton is replaced by normal constructor.
Singletone was prone to mutex locks when parallel processing.
Casting between shared and unique pointer vice versa is not supported by pybind.
=> Fix for import ParticleDef error for newer pyBindings Version.  #43

tests/Annihilation_TEST.cxx, tests/Bremsstrahlung_TEST.cxx, tests/Compton_TEST.cxx, tests/ContinuousRandomization_TEST.cxx, tests/DecayChannel_TEST.cxx, tests/Epairproduction_TEST.cxx, tests/Ionization_TEST.cxx, tests/Mupairproduction_TEST.cxx, tests/PhotoPair_TEST.cxx, tests/Photonuclear_TEST.cxx, tests/Propagation_TEST.cxx, tests/Scattering_TEST.cxx, tests/Sector_TEST.cxx, tests/WeakInteraction_TEST.cxx
Some tests on travis #68 here passed although the input files were not found.
This provides a clear error with a nice error message  when the input files could not be found.
=> Make tests fail when files not found

private/PROPOSAL/Sector.cxx, private/PROPOSAL/medium/MediumFactory.cxx
Fixing two bugs in Propagation. First bugs caused the density of a created medium to be overwritten, the second bug caused PROPOSAL to freeze when the distance to the Sector border became too small.
=> Fix bugs in Propagation

private/PROPOSAL/Sector.cxx, private/PROPOSAL/propagation_utility/PropagationUtilityInterpolant.cxx
Instead of calculating the energy for a given distance and calculating back the distance for the energy (in case the max distance to propagate in the sector is the chosen next procedure) the distance is directly taken to avoid differences due to numerical uncertainties.
=> change distance calculation in sector

private/PROPOSAL/Propagator.cxx, private/PROPOSAL/geometry/Sphere.cxx, resources/config_docu.md
There're three commits in this PR, which includes the following changes:
1. Add a missing conversion from meter to centimeter of inner_radius in Sphere.cxx
2. Add a note about the unit used by the config file in the [documentation](https://github.com/tudo-astroparticlephysics/PROPOSAL/blob/master/resources/config_docu.md)
3. Modify a config label from `continous_loss_output` to `do_continuous_energy_loss_output`, so that it can be properly read by the program.
4. Modify a label `cuts_before` to `cuts_infront` in the configuration parser in Propagator.cxx.
=> Add a missing conversion from meter to centimeter

.travis.yml
The reason, why the build bots currently fail:
see https://travis-ci.community/t/pyenv-global-3-7-now-fails-on-xenial-it-was-working-3-days-ago/9430
or the fix https://github.com/vgc/vgc/commit/5e3270528563bc1ddea687f207ea612176883330
=> fix: adapt pyenv for travis update

private/PROPOSAL/crossection/EpairIntegral.cxx, tests/CMakeLists.txt
When calculating dEdx for EPairProduction, CalculatedEdx may run into a specific case called `rflag` where the integral for dEdx is split into two parts (one part is integrated from v_min to 0.8, the second from 0.8 to v_up).
For the second part, the substitution `v = 1-v` is used for numerical reasons. However, it seems that this substitution was missing for FunctionToDEdxIntegralReverse.
This caused wrong calculations of dEdx in very specific cases, for example when calculating only-continuous dEdx values for electrons for high energies.
This breaks some test files.
=> Fix error missing substitution for rFlag case in EPairProduction

CMakeLists.txt, private/PROPOSAL/propagation_utility/PropagationUtilityInterpolant.cxx
Fix an issue where the accuracy passed to the Newton Raphson method could not be reached because it was too high compared to the double precision for high energies. Fixes #106
=> Fix numerical problems for PropagationUtilityDisplacement

CMakeLists.txt, private/PROPOSAL/scattering/Scattering.cxx, tests/CMakeLists.txt, tests/gen_testfiles_scripts/propagation.py
Add call to CalculateSphericalCoordinates() at the beginning of Scattering:Scatter to ensure that return values of GetTheta() and GetPhi() are well-defined if spherical components have not been calculated yet.
Could be the solution for issue #119
There will be a better, conceptional fix for this issue in version 7.X
=> Add call to CalculateSphericalCoordinates() at the beginning of Scattering:Scatter

src/PROPOSAL/detail/PROPOSAL/decay/ManyBodyPhaseSpace.cxx
In ManyBodyPhaseSpace::SampleEstimateMaxWeight, the PhaseSpaceParameters struct has not been intialized. This undefined behavior was able to cause bugs depending on the build system. The initial guesses are now initialized using the first iteration.
=> Fit not initalized values in ManyBodyPhaseSpace::SampleEstimateMaxWeight

setup.py, src/pyPROPOSAL/CMakeLists.txt
There has been a [bugfix in conan](https://github.com/conan-io/conan-center-index/pull/4445) which means that installation of pybind11 with conan should now be possible again.
Therefore, I removed the workaround in pypi as well as the warning message in the CMakeLists.txt
=> Remove fixes and warnings related to former bug with pybind11 in conan

CMakeLists.txt
I've been looking into the visibility settings for PROPOSAL, trying to find an acceptable solution.
**Original problem and current quick-fix**
The reason we started thinking about this problem was a huge amount of linker errors when trying to build PROPOSAL (as a static library) with pybind11-bindings on MacOS (see  issue #141).
These warnings were gone by [adding](https://github.com/tudo-astroparticlephysics/PROPOSAL/blob/44265c664ce5d9664926c852c263ad99aa800f90/CMakeLists.txt#L35) these lines to the CMakeLists:
```
if(NOT BUILD_SHARED_LIBS)
set(CMAKE_CXX_VISIBILITY_PRESET hidden)
endif()
```
However, I am not sure why this actually solved the initial problem (the visibility setting should have no influence when building a static library, does it?)
**Trying to find a better solution for …
=> WIP: Find appropriate solution for visibility settings / Rework CMakeLists.txt

src/PROPOSAL/PROPOSAL/PROPOSAL.h, src/PROPOSAL/PROPOSAL/math/Spherical3D.h, src/PROPOSAL/PROPOSAL/scattering/DirectionChange.h, src/PROPOSAL/PROPOSAL/scattering/Scattering.h, src/PROPOSAL/PROPOSAL/scattering/ScatteringMultiplier.h, src/PROPOSAL/PROPOSAL/scattering/stochastic_deflection/Parametrization.h, src/PROPOSAL/PROPOSAL/scattering/stochastic_deflection/bremsstrahlung/TsaiApproximationBremsstrahlung.h, src/PROPOSAL/PROPOSAL/scattering/stochastic_deflection/ionization/NaivIonization.h, src/PROPOSAL/PROPOSAL/scattering/stochastic_deflection/nuclearInteraction/BorogPetrukhinNuclearInteraction.h, src/PROPOSAL/PROPOSAL/scattering/stochastic_deflection/pairProd/KelnerPairProduction.h, src/PROPOSAL/detail/PROPOSAL/scattering/stochastic_deflection/bremsstrahlung/TsaiApproximationBremsstrahlung.cxx, src/PROPOSAL/detail/PROPOSAL/scattering/stochastic_deflection/ionization/NaivIonization.cxx, src/PROPOSAL/detail/PROPOSAL/scattering/stochastic_deflection/nuclearInteraction/BorogPetrukhinNuclearInteraction.cxx, src/PROPOSAL/detail/PROPOSAL/scattering/stochastic_deflection/pairProd/KelnerPairProduction.cxx, src/pyPROPOSAL/detail/pybindings.cxx, src/pyPROPOSAL/detail/scattering.cxx
To call the stochastic deflection in python the return type was not pybinded resulting in:
`TypeError: Unable to convert function return value to a Python type! The signature was
(self: proposal.scattering.StochasticDeflection, initial_energy: float, loss_energy: float, random_numbers: List[float]) -> PROPOSAL::DirectionChangeAngular`
an example code would be
```
import proposal as pp
mudef = pp.particle.MuMinusDef()
med = pp.medium.StandardRock()
param = pp.make_stochastic_deflection('kelnerpairproduction', mudef, med)
deflect = param.stochastic_deflection(1e6, 1e5, [0.1, 0.2, 0.3, 0.1])
```
=> add pybindings for the `DirectionChangeAngular`

src/PROPOSAL/detail/PROPOSAL/particle/Particle.cxx
If the ParticleType is not set for a ParticleState, calculations of momenta did silently assume that the underlying particle
has no mass. This can easily cause mistakes without any notice. Instead, a exception should be thrown.
Furthermore, this makes the code a bit more readable and also less repetetive.
=> Avoid unknowingly wrong calculations of momenta in ParticleState

src/PROPOSAL/detail/PROPOSAL/decay/ManyBodyPhaseSpace.cxx, src/PROPOSAL/detail/PROPOSAL/decay/TwoBodyPhaseSpace.cxx
In the LeptonicDecayChannel` the decay calculation, taking the particle def and the particle state, was already changed that the state doesn't need the particle def information.
In `ManyBodyPhaseSpace` and `TwoBodyPhaseSpace`this wasn't changed, too.
=> fix decay if no particle type is given in the particle state

src/PROPOSAL/detail/PROPOSAL/propagation_utility/PropagationUtilityInterpolant.cxx, tests/Interaction_TEST.cxx
We noticed that the Propagation can still produce boost exceptions when executing the `cubic_splines::find_parameter` method, although only in very rare cases.
After some investigation, I found out the reason for this.
When trying to run `UtilityInterpolant::GetUpperLimit` for interpolated functions, the Newton Raphson method can run into local minima when the spline is overshooting, see for example here:
This happens only rarely when the sampled random number is very specific.
My first idea and attempt at a solution was to fall back to the integrated function, `UtilityIntegral`, however mixing Interpolation and Integration can lead to inconsistencies in the long run.
Instead, I implemented a fall back to a simple Bisection method. This will be slower than the NewtonRaphson method, but …
=> Fix boost interpolation error

conanfile.py
Building fails on the master now because CMake is having trouble with the difference of `gtest` and `GTest`. Apparently, this has been a bug in conan that has been fixed in the package for gtest/1.11.0 [here](https://github.com/conan-io/conan-center-index/pull/7894).
If there are no objections, I would propose to push the GTest version to the newest release to fix this issue.
=> Push GTest version to 1.11.0

src/PROPOSAL/detail/PROPOSAL/Propagator.cxx, src/PROPOSAL/detail/PROPOSAL/propagation_utility/Interaction.cxx
Fixes #227 
During propagation, the sampling of the stochastic loss consists of two steps:
1. Sample an energy where the next stochastic loss occurs using `Interaction::EnergyInteraction` ([here](https://github.com/tudo-astroparticlephysics/PROPOSAL/blob/e326289c172cfdc477f9fa4dea01ed62d9153b2c/src/PROPOSAL/detail/PROPOSAL/Propagator.cxx#L80))
2. Sample a stochastic loss (i.e. type and size of the loss) for this energy using `Interaction::Rates` and `Interaction::SampleLoss` ([here](EnergyStochasticloss))
However, in rare cases, the first step can sample an energy where actually, no stochastic interactions are possible anymore. In this case, in the second step, `Interaction::Rates` returns only zeroes and `Interaction::SampleLoss` throws an error as seen in issue #227.
The reason behind …
=> Return empty Loss object in Interaction::SampleLoss if no stochastic interaction is possible

src/PROPOSAL/detail/PROPOSAL/Propagator.cxx
Until now, if one tried to create a Propagator but passed an invalid path, the error message thrown by PROPOSAL looked something like this:
```
[2021-12-22 18:04:06.308] [proposal.propagator] [critical] Unable to parse /wrong/path/ as json file
libc++abi.dylib: terminating with uncaught exception of type nlohmann::detail::parse_error: [json.exception.parse_error.101] parse error at line 1, column 1: syntax error while parsing value - unexpected end of input; expected '[', '{', or a literal
```
This is rather confusing, and especially the json exception gives the expression there is a syntax error rather than just a wrong path.
With this, the message looks like this
```
libc++abi.dylib: terminating with uncaught exception of type std::invalid_argument: No configuration file found under …
```
=> Improve exception thrown when path to configuration file is not readable

pyproject.toml, setup.py
When trying to install proposal with pip in virtual environments, I realized that python does not find the installed modules.
Looking at the verbose output of `pip install`, CMake said:
```
-- Found Python: /usr/bin/python3.10 (found version "3.10.1") found components: Interpreter Development Development.Module Development.Embed
```
which means that CMake does not use the python version of the virtual environment, but rather the global python version!
The CMake output also said
```
CMake Warning:
Manually-specified variables were not used by the project:
PYTHON_EXECUTABLE
PYTHON_INCLUDE_DIR
PYTHON_LIBRARY
```
so the variables from the `setup.py` that should set the correct python version are in fact ignored!
From the [manual page of …
=> Change setup.py to be able to find correct python versions

src/PROPOSAL/PROPOSAL/crosssection/CrossSectionDNDX/CrossSectionDNDXInterpolant.h, src/PROPOSAL/detail/PROPOSAL/crosssection/CrossSectionDNDX/CrossSectionDNDXInterpolant.cxx, tests/Compton_TEST.cxx, tests/Ionization_TEST.cxx
While doing an overhaul of the UnitTest, I discovered that the Ionization stochastic losses have not been tested due to a misplaced `break` instruction. When enabling these tests, they failed for specific random numbers, so I had a closer look.
The following plots are for muons in ice, with an EnergyCut of 500 MeV and an initial energy of 1e11 MeV. The parametrization is BetheBlochRossi.
Looking at the ionization losses v sampled for a specific random number (rnd between 0 and 1), they look like this:
If we look at the ratio of the sampled v values for the integral and interpolant, we see this pattern:
which means that the losses are off by almost 2 percent.
If we look at the cumulative cross section (i.e. the integral of the differential cross section from v_cut to a specific v), …
=> Improve v node distribution for ionization interpolant and fix test issues

src/PROPOSAL/PROPOSAL/Secondaries.h, src/PROPOSAL/detail/PROPOSAL/Secondaries.cxx, src/pyPROPOSAL/detail/particle.cxx, tests/Secondaries_TEST.cxx
Fixes #238 
This adds a function which checks whether a particle track has a hit a certain geometry or not. 
We decided that particles where the propagation ended on the border of a geometry (i.e. the particle did not enter the geometry, but "touched" it) will be counted as a hit.
=> Add function "HitGeometry" to Secondaries

src/PROPOSAL/PROPOSAL/crosssection/parametrization/Bremsstrahlung.h, src/PROPOSAL/PROPOSAL/crosssection/parametrization/EpairProduction.h, src/PROPOSAL/detail/PROPOSAL/crosssection/parametrization/Bremsstrahlung.cxx, src/PROPOSAL/detail/PROPOSAL/crosssection/parametrization/EpairProduction.cxx, src/pyPROPOSAL/detail/parametrization.cxx
This way, we do not need to create new instances if the density correction changes.
For users of the crosssection/parametrization classes, only the hash calculation changes.
This is a preparing change for LPM in inhomogeneous media (#54), where we do not want to re-create this class for every evaluation point.
=> Move density_correction parameter for LPM classes from Constructor to method

src/PROPOSAL/PROPOSAL/scattering/Scattering.h, src/PROPOSAL/PROPOSAL/scattering/multiple_scattering/ScatteringFactory.h, src/PROPOSAL/detail/PROPOSAL/propagation_utility/PropagationUtility.cxx, tests/Scattering_TEST.cxx
Before this, one could not explicitly choose `NoScattering`as a scattering method in the configuration file.
=> add NoScattering case to make_multiple_scattering function

src/PROPOSAL/detail/PROPOSAL/Propagator.cxx
When the algorithm at the sector border returns back to the case where a stochastic loss in the next interaction, we do not need to recalculate the energy (and grammage) to the next interaction since we already made the calculations.
Next to the wasted computational time, this calculation can also be numerically unstable (which lead to runtime errors in rare cases).
When solving issue #246, this whole code section is probably going to be restructured anyway. But for now, this should be a quick fix.
=> Avoid (possible) unnecessary recalculations when crossing sector borders

src/PROPOSAL/detail/PROPOSAL/crosssection/parametrization/PhotoQ2Integration.cxx
When using specific photonuclear crosssections with tau leptons, the differential crosssection becomes negative, which happend at low energies close to the tau mass. This causes dNdx to be negative as well. CubicInterpolation seems to have problems with these negative values, and crashes when trying to initialize the tables.
For example, this is the differential crosssection for taus in ice, using an EnergyCut of (Inf, 0.05), the ButkevichMikheyev parametrization and DuttaRenoSarvecivSeckel for the shadowing, at an energy of 1.1 tau masses:
This PR simply catches negative values of the differential crosssection and sets them to zero.
=> Catch negative values of the differential crosssection for PhotoQ2Intgration

src/PROPOSAL/detail/PROPOSAL/crosssection/parametrization/Photoproduction.cxx
This caused linker errors under certain conditions, which seems to be fixed when explicitly using 'std::string'.
Simplified the rest of the template to be easier to read.
=> Fix linker error for specific build configurations

src/PROPOSAL/PROPOSAL/crosssection/parametrization/Photoproduction.h, src/PROPOSAL/detail/PROPOSAL/crosssection/parametrization/Photoproduction.cxx
The cross section values of PhotoproductionRhode are provided as tables values which are interpolated. The lowest energy for which an interpolation point is given is at 0.1 GeV. For energies below, until now, the cross section has just been extrapolated, leading to unphysical results. This can be seen in this plot by @asandrock:
This PR now ensures that we do not extrapolate the Rhode parametrization below our lowest point at 0.1 GeV.
However, this does not fix an issue with other photoproduction parametrizations.
Right now, their dNdx values look like this:
We see that there is still an extrapolation for all other cross sections, which lead to an unphysical increase of the cross section towards lower energies. How should we behave here?
We could set the cross section to zero below a …
=> Fix extrapolation to lower energies for PhotoproductionRhode

.github/workflows/cpp.yml, conanfile.py
Github actions recently updated the default Windows runner from Windows Server 2019 to Windows Server 2022.
It looks like this not yet completely compatible with conan, at least they don't provide prebuilt packages for Visual Studio 17 which comes with WS2022.
Therefore, I would suggest that we keep testing on Windows Server 2019 until conan figured out all possible issues and provides the binaries.
=> Fix windows CI

docs/config_docu.md
Cylinder: change order of arguments in json documentation to be consistent with argument order of constructor
The order in the json file is actually arbitrary, but this might avoid confusion (since for the rest of the documentation, the order it similar, whenever applicable)
=> Cylinder: change order of arguments in json documentation

src/PROPOSAL/PROPOSAL/Propagator.h, src/PROPOSAL/detail/PROPOSAL/Propagator.cxx
The `Propagator::AdvanceParticle` method is responsible for doing the continuous steps of the particle propagation. This includes the calculation of the continuous energy losses as well at the particle displacement, where we also have to correctly consider the effects of multiple scattering and take into account border transitions.
However, the border transitions (in combination with multiple scattering) have been the focus of several issues in the past. One current issue that has to do with scattering and border transitions has been described in detail in issue #246.
Another issue on the master branch occurred when I tried to solve this issue.
Let's assume we have a particle that propagated to a sector border in the previous step. During the next continuous step, it can be possible that …
=> Rewrite Propagator::AdvanceParticle method

src/PROPOSAL/PROPOSAL/crosssection/parametrization/Parametrization.hpp, tests/CMakeLists.txt, tests/PhotoMuPair_TEST.cxx, tests/gen_testfiles_scripts/photomupair.py
Add some UnitTests for PhotoMuPairProduction.
We check dNdx and the dNdx interpolant, we check that the interaction is only-stochastic (i.e. no dEdx), we check that losses are always catastrophic (i.e. v=1) and we check the x sampling.
While writing the tests, I also realized that the PhotoMuPairProduction parametrization has not yet been registered as "only_stochastic", so this has been fixed.
=> Add UnitTests for PhotoMuPairProduction

src/PROPOSAL/detail/PROPOSAL/scattering/multiple_scattering/Highland.cxx, tests/Scattering_TEST.cxx
For zero displacement, y will be zero, which will create a nan here.
This is now avoided the same way it is avoided in HighlandIntegral::CalculateTheta0.
=> Catch calculation that can become `nan` in Highland::CalculateTheta0

src/PROPOSAL/PROPOSAL/scattering/multiple_scattering/Highland.h, src/PROPOSAL/PROPOSAL/scattering/multiple_scattering/HighlandIntegral.h, src/PROPOSAL/PROPOSAL/scattering/multiple_scattering/Moliere.h
This PR adds a missing clone function for multiple_scattering::HighlandIntegral. Due to the inheritance structure, this meant that the clone function of multiple_scattering::Highland has been called instead, which caused issue #284. 
Also added some simplifications for the clone function.
Fixes issue #284.
=> Add missing clone function to HighlandIntegral

src/PROPOSAL/PROPOSAL/Secondaries.h, src/PROPOSAL/detail/PROPOSAL/Secondaries.cxx, tests/Secondaries_TEST.cxx
Most of the calculations in `Secondaries` didn't take multiple scattering correctly into account.
This influenced most of the calculations, including the calculation of exit points, entry points and approach points.
When calculating the possible entry point of a particle, the directions of the individual track points have been used.
However, since multiple scattering also introduces a displacement of the particle, these directions are not identical to the direct path between two track points.
This leads to a situation like in this sketch: We want to calculate the entry point with a specific geometry (red circle). However, the algorithm used the red arrow, which is the direction at track point 1. What should be done, and which is now implemented, is to use the direct line between two track …
=> Fix Secondaries calculation when Multiple Scattering is enabled

src/PROPOSAL/PROPOSAL/scattering/stochastic_deflection/bremsstrahlung/BremsGinneken.h, src/PROPOSAL/detail/PROPOSAL/scattering/stochastic_deflection/bremsstrahlung/BremsGinneken.cxx
The parametrizations of Van Ginneken are check for energies `3 GeV < E < 30 TeV`. For high energy losses `nu > 0.5` and low energies `E < 0.7 GeV`, it is not possible to determine the parameter `nu_g` in the bremsstrahlungs parametrization. In that case, the value is set as `nu_g = 0.5`. 
In the propagation tool MUSIC, this is the standard value for all cases.
=> error in bremsstrahlung deflection for low energies 

src/PROPOSAL/PROPOSAL/Constants.h, src/PROPOSAL/detail/PROPOSAL/Constants.cxx, src/PROPOSAL/detail/PROPOSAL/propagation_utility/ContRandBuilder.cxx, src/PROPOSAL/detail/PROPOSAL/propagation_utility/DecayBuilder.cxx, src/PROPOSAL/detail/PROPOSAL/propagation_utility/DisplacmentBuilder.cxx, src/PROPOSAL/detail/PROPOSAL/propagation_utility/InteractionBuilder.cxx, src/PROPOSAL/detail/PROPOSAL/propagation_utility/PropagationUtilityInterpolant.cxx, src/PROPOSAL/detail/PROPOSAL/propagation_utility/TimeBuilder.cxx, src/pyPROPOSAL/detail/pybindings.cxx
We have the nodes options in InterpolationSettings to set the number of nodes for out crosssections interpolation tables.
However, the number of nodes for the utility interpolation tables are currently hardcoded.
This MR introduces the option to adapt this parameter in a similar way, using the `InterpolationSettings::NODES_UTILITY` function. The default value is 500 for all utilities, which means that only the default number of nodes in the ContRand interpolant is changed.
The number of nodes has also been added to the hash so that multiple tables with a different number of nodes can exist at the same time.
=> Add InterpolationSettings::NODES_UTILITY

src/PROPOSAL/detail/PROPOSAL/Secondaries.cxx, tests/Secondaries_TEST.cxx
Very identical to issue #278 
When using the `Secondaries::HitGeometry` method, multiple scattering was not correctly taken into account.
With this PR, we now use the actual track between particle positions.
In issue #288, we created this propagation environment:
> ```
> geometry = pp.geometry.Sphere(pp.Cartesian3D(0, 0, 0), 1e20)
> geometry.hierarchy = 1
> 
> detector_level = pp.geometry.Cylinder(pp.Cartesian3D(0, 0, -100000 + 0.5), 1, 1e20)
> detector_level.hierarchy = 10
> ```
> 
>
> 
> ```
> secs = prop.propagate(init_state, hierarchy_condition=5)
> ```
and checked with  `secs.hit_geometry(detector_level)` whether our particles have reached the detector level.
On the master, the z-distributions looked like this:
Here we see particles with z != -100000 in the first histogram although …
=> 288 hitgeometry unreliable with multiple scattering

.github/workflows/cpp.yml, conanfile.py
This PR includes some updates, with which the CI is also running again. This includes
- Explicitly setting `settings.compiler.cppstd` for conan (see issue #291)
- Updating boost version for testing
- Updating cubicinterpolation version (this only includes changes to the build process, but not to the module itself)
=> Update modules and fix CI

.github/workflows/cpp.yml, conanfile.py
The CI has been broken for some time now. This should fix it now with the following steps:
- Using the newest version of spdlog in our conanfile. With the old version, there was some problem with finding the `fmt` package. This caused the gcc builds to fail with the conan error:
```
Could NOT find fmt: Found unsuitable version "None", but required is at
least "5.3.0" (found None)
```
- Using `windows-latest` for the CI runner. As desribed in issue #262, we haven't been using the latest windows runner. However, on the old version, weird linker errors started to appear. They are gone with the newest version.
- Disabling conan caches for the windows-runner. Building PROPOSAL and its dependencies works without a problem. However, reloading the caches fails with conan throwing the error …
=> Fix CI again

src/PROPOSAL/detail/PROPOSAL/crosssection/parametrization/Compton.cxx
Fixes issue #301 
The lower energy limit of Compton is somewhat arbitrary, and has been set to 2*ME before. Now, we set it to the ionization energy of the K-shell electron of hydrogen to have a new lower limit which works better with the now-implemented Photoeffect.
=> Adapt LowerEnergyLim of Compton

src/PROPOSAL/PROPOSAL/crosssection/parametrization/Bremsstrahlung.h, src/PROPOSAL/detail/PROPOSAL/crosssection/parametrization/Bremsstrahlung.cxx
For BremsElectronScreening, the kinematic limits have so far been taken from Petrukhin & Shestakov, where the upper limit has been calculated by setting the corresponding screening function to zero.
However, we don't need to use this for BremsElectronScreening. Instead, we can just use the physical limit 1 - m/E. 
We have checked that this is still consistent with the condition that the screening function should be non-negative (see [this presentation](https://indico.scc.kit.edu/event/2955/contributions/11154/attachments/5345/8203/EM_comparison.pdf) for more information)
Comparing PROPOSAL with EGS4, using these improved limits also yields a better agreement in the cross section (also shown in the presentation linked above).
This PR also fixes that the tables with the correction factors …
=> Change kinematic limits of BremsElectronScreening

src/PROPOSAL/PROPOSAL/crosssection/parametrization/Bremsstrahlung.h, src/PROPOSAL/detail/PROPOSAL/crosssection/parametrization/Bremsstrahlung.cxx
We have two types of KinematicLimits for Bremsstrahlung:
Firstly those who follow from the condition that E>m0 for all particle involved needs to be fulfilled, and secondly those who are derived by requiring the screening functions to be non-zero.
The first condition is more general, and is now implemented as `Bremsstrahlung::GetKinematicLimits`, i.e. as the default method for all Bremsstrahlungs parametrizations.
If the kinematic limits using the screening function condition is supposed to be used, the `GetKinematicLimits` method will now be overwritten by the specific parametrizations classes (which is currently the case for all parametrizations but `ElectronScreening`).
This way, the structure becomes more clear: The base class has the most general implementation of kinematic limits, …
=> Restructure Bremsstrahlung::GetKinematicLimits

src/PROPOSAL/detail/PROPOSAL/methods.cxx
In one case the wrong path has been used, and in the other case I forgot the path.
=> Fix typos in new logging messages

src/PROPOSAL/PROPOSAL/particle/Particle.h
Add missing entry for InteractionType::Photoeffect to Type_Interaction_Name_Map
Without this, it is currently impossible to search for Photoeffect losses in `Secondaries::GetStochasticLosses(const std::string& interaction_type)`,  so that one has to use `Secondaries::GetStochasticLosses(const InteractionType& type)` instead.
Most of the other uses of this map affect logging messages for building tables - But there are no tables built for the photoeffect.
=> Add missing entry for InteractionType::Photoeffect

src/PROPOSAL/detail/PROPOSAL/crosssection/parametrization/Photoeffect.cxx
Using the approximation sinh(x) ~ exp(x)/2 for large values of x and combining this with the argument of the exponential function already present, the floating point exception from overflow is averted. This approximation is accurate to 1e-9 for x > 10, which is much more accurate than the photoeffect cross section parametrization itself.
=> Made correction factor non-relativistic electrons numerically stable at very low energies

.github/workflows/cpp.yml, .github/workflows/pypi_deploy.yml
The ubuntu-18.04 runner of GitHub actions starts deprecation in a few days (which will include temporary brownouts), with complete deprecation at the end of this year (see [this issue](https://github.com/actions/runner-images/issues/6002)).
Therefore, we should update our runners.
Since gcc5 is not trivially available on 20.04 anymore, it is now downloaded and installed manually. We should still test gcc5 because this is the oldest gcc version that is still tested by conan.
For gcc7, we can use a simpler tool that installs and initializes gcc7.
=> Update ubuntu-18.04 runner to ubuntu-20.04

src/PROPOSAL/detail/PROPOSAL/propagation_utility/InteractionBuilder.cxx
We have implemented a check for negative dNdx values in PR #277, which sets dNdx to zero and issues a warning if an interpolant returns a negative value (for example due to oscillations in the interpolant).
However, there is no such check for the MeanFreePath (which is a separate interpolant). This has already caused problems in CORSIKA 8, which lead to the discovery of the issue described in PR #317. However, it would have been much easier to catch this with a correct error message.
While it is straightforward to just set dNdx to zero if it becomes negative, I am not sure whether there is a consistent solution for the mean free path if it becomes negative. Using either INF or 0 as an alternative return value seems like is could cause unwanted behavior. Therefore, I implemented an …
=> Fix and issue warning if mean free path becomes negative

src/PROPOSAL/PROPOSAL/crosssection/CrossSection.h, src/PROPOSAL/PROPOSAL/crosssection/CrossSectionDirect.h, src/PROPOSAL/PROPOSAL/crosssection/CrossSectionMultiplier.h, src/PROPOSAL/PROPOSAL/propagation_utility/ContRand.h, src/PROPOSAL/detail/PROPOSAL/propagation_utility/ContRand.cxx, src/pyPROPOSAL/detail/crosssection.cxx, tests/ContinuousRandomization_TEST.cxx
When creating a EnergyCutSettings object, a boolean `continuous_randomization` indicated whether dE2dx tables should be built.
However, one can still initialize a ContRand object if this option has been set to false. In this case, the object will exist, but actually make no continuous randomization. 
This is not useful, and is probably not wanted by the user. Therfore, this PR adds a check whether at least one dE2dx table has been built, and if this is not the case, an exception is thrown:
```
Can not build ContRand because no dE2dx tables have been built. You need to use continuous_randomization=True when creating the EnergyCutSettings object to be able to use continuous randomization.
```
This also means that the ContRand object needs to know about the EnergyCutSettings that are being …
=> Check if dE2dx tables have been built when creating ContRand builder

src/PROPOSAL/PROPOSAL/crosssection/CrossSectionDirect.h
When building PROPOSAL, clang currently gives a bunch of warnings such as 
```
warning: 'CalculatedNdx' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
double CalculatedNdx(double energy, size_t hash) {
```
which is due to missing `override` keyword in CrossSectionDirect.h.
This is for example visible in [this runner](https://github.com/tudo-astroparticlephysics/PROPOSAL/actions/runs/3418261048/jobs/5690338119).
This commit should fix them.
=> Fix clang warning due to missing override keyword

tests/Bremsstrahlung_TEST.cxx, tests/Compton_TEST.cxx, tests/Epairproduction_TEST.cxx, tests/Ionization_TEST.cxx, tests/Mupairproduction_TEST.cxx, tests/Photonuclear_TEST.cxx
In PROPOSAL 6 and before, an "infinite ecut" has been represented by `ecut = -1`. With PROPOSAL 7, we changed this to `ecut = INF`, with `INF = PROPOSAL::INF = std::numeric_limits<double>::infinity()`.
At first, in the TestFiles, an infinite `ecut` was still stored as `-1` and manually converted to `INF` within the UnitTests. This has been changed with PR #242, where it has been changed to store `inf` to the TestFiles as well. 
However, while writing `INF` to a file is not a problem in C++, parsing `inf` from a file directly to a double using ifstream is not possible. This means that the UnitTests stopped as soon as they encountered `ecut == INF`. 
The easiest solution I've been able to find is to parse the value for `ecut` to a `std::string` first, and then convert it do a double using …
=> Fix ifstream in UnitTests to correctly read in `ecut==INF`

docs/config_docu.md, src/PROPOSAL/PROPOSAL/crosssection/Factories/PhotoPairProductionFactory.h, src/PROPOSAL/PROPOSAL/crosssection/ParticleDefaultCrossSectionList.h, src/PROPOSAL/PROPOSAL/crosssection/parametrization/PhotoPairProduction.h, src/PROPOSAL/detail/PROPOSAL/Propagator.cxx, src/PROPOSAL/detail/PROPOSAL/crosssection/Factories/PhotoPairProductionFactory.cxx, src/PROPOSAL/detail/PROPOSAL/crosssection/parametrization/Bremsstrahlung.cxx, src/PROPOSAL/detail/PROPOSAL/crosssection/parametrization/PhotoPairProduction.cxx, src/pyPROPOSAL/detail/parametrization.cxx, tests/Bremsstrahlung_TEST.cxx, tests/CMakeLists.txt, tests/Compton_TEST.cxx, tests/Epairproduction_TEST.cxx, tests/Ionization_TEST.cxx, tests/Mupairproduction_TEST.cxx, tests/PhotoPair_TEST.cxx, tests/Photonuclear_TEST.cxx, tests/gen_testfiles_scripts/photopair.py
New PR for #334 but with clean history.
This PR adds the LPM effect for pair production of electron-positron pairs by photons.
Furthermore, this PR fixes the following issues in the implementation of the LPM effect in Bremsstrahlung:
1. An inconsistent definition of eLPM has been fixed
2. A more general definition of s1 is now used, to that the BremsLPM parametrization is not only valid for muons, but also for other particles (electrons/positrons/taus)
=> Add LPM effect for photopair, fixes for BremsLPM 

src/pyPROPOSAL/detail/parametrization.cxx
`photopair_lpm` was added to `m_sub_brems` instead of `m_sub_photopair`, which means that it was found under `pp.parametrization.bremsstrahlung.photopair_lpm` instead of `pp.parametrization.photopair.photopair_lpm`
=> Add photopair_lpm to correct module

conanfile.py, setup.cfg
pybind11 started supporting Python3.11 with version 2.10.1 (see [here](https://github.com/pybind/pybind11/releases/tag/v2.10.1))
This updates the version used in the conanfile, so `pip install proposal` works out of the box with python3.11.
=> Update pybind11 version in conanfile to support python 3.11

src/PROPOSAL/PROPOSAL/Constants.h, src/PROPOSAL/detail/PROPOSAL/Constants.cxx, src/PROPOSAL/detail/PROPOSAL/Propagator.cxx, src/pyPROPOSAL/detail/pybindings.cxx
Issue #332 shows that the propagation can stall if the `PARTICLE_POSITION_RESOLUTION` can not be reached due to numerical uncertainties (for very large propagation steps, complicated medium intersections, non-dense media, with multiple scattering enabled). I've been trying to find a "good" way to solve this problem, but was not successful to find a solution that made me happy. 
As a "quick fix", this PR adds an (adjustable) number of maximum iteration steps in `Propagator::AdvanceParticle`.
After we reached the maximum number of propagation steps, we check the deviation from `PARTICLE_POSITION_RESOLUTION` is. If it is "still acceptable" (which is currently defined as "1 cm"), we still continue propagation. This avoids that the propagation always stops if we have the problem in issue #332. …
=> Add maximum number of iteration steps in `Propagator::AdvanceParticle`

src/PROPOSAL/detail/PROPOSAL/crosssection/parametrization/EpairProduction.cxx
The variable `xi` is used twice in the parametrization, once with `rho` and once with `rho_max`.
The call to `suppression_factor` gets `xi`, however this is supposed to be the `xi` calculated with `rho`, not with `rho_max`.
=> Fix call to LPM in EpairForElectronPositron

src/PROPOSAL/detail/PROPOSAL/secondaries/parametrization/compton/NaivCompton.cxx, tests/SecondaryProduction_TEST.cxx
This PR fixes the secondaries calculator in the Compton secondaries calculator.
So far, the rest mass of the atomic electron has been neglected. 
The formulae for the angles calculation also weren't accurate.
The new implementation is also validated with a UnitTest, which checks for energy and momentum conservation (which is the assumption we put into this interaction)
=> Fix energy-momentum conservation in Compton secondaries production

src/pyPROPOSAL/detail/parametrization.cxx
Fixes #351 
The Photoproduction parametrizations use a rather complicated inheritance structure, including multiple inheritance. This is due do the fact that some parametrization "borrow" from other parametrizations.
However, this needs to be explicitly mentioned to pybind11, see [here](https://github.com/pybind/pybind11/issues/2071).
If this is done correctly, all functions calls work correctly.
=> Indicate multiple inheritance structure of `crosssection::Photoproduction` classes in pybindings

src/PROPOSAL/PROPOSAL/secondaries/parametrization/photopairproduction/PhotoPairProduction.h, src/PROPOSAL/PROPOSAL/secondaries/parametrization/photopairproduction/PhotoPairProductionInterpolant.h
I noticed that in `PhotoPairProductionInterpolant::CalculateEnergy`, there is a step where we "randomize" how we distribute the energy between the electron and positron.
However, for this parametrization, `rho` (or in literature rather known as `x`, the ratio of the electron and photon energy) is already between [0, 1). This means we don't need to randomize the distribution.
This is probably a remnant from other classes, where `rho` is just sampled between [0, 1) due to the symmetry of the function. However, this is not implemented for PhotoPairProduction (although it could be implemented).
Therefore, we don't need 5, but 4 random numbers here.
=> Remove extra sampling of asymmetry in photopairproduction secondary energy calculation

docs/config_docu.md
This adds the missing documentation for `AbtFT` and `BlockDurandHa` in `config_docu.md`
=> Add missing documentation for photonuclear cross sections [ci skip]

docs/config_docu.md, src/PROPOSAL/PROPOSAL/scattering/multiple_scattering/Moliere.h, src/PROPOSAL/PROPOSAL/scattering/multiple_scattering/Parametrization.h, src/PROPOSAL/PROPOSAL/scattering/multiple_scattering/ScatteringFactory.h, src/PROPOSAL/detail/PROPOSAL/scattering/multiple_scattering/Moliere.cxx, src/pyPROPOSAL/detail/scattering.cxx, tests/Scattering_TEST.cxx
When profiling the performance of multiple scattering calculations, we already knew that `Moliere` takes much longer to calculate than `Highland` or `HighlandIntegral`. For applications such as CORSIKA 8, where an accurate description of large-scattering angles is mandatory, this starts to becomes a performance issue.
When profiling the execution of `Moliere`, I figured out that most of the time is spent in the functions `f1M`, `f2M`, `F1M` `F2M`, where an expression is evaluated using Horner's method. Looking at the manual of EGS, I found out that they use interpolation tables to store the values of these functions instead of evaluating them for every execution.
Therefore, I implemented a similar approach for PROPOSAL, using the `cubicinterpolation` classes. 
First of all, these are …
=> Create `MoliereInterpol` parametrization for multiple scattering

src/PROPOSAL/PROPOSAL/secondaries/parametrization/photopairproduction/PhotoPairProductionKochMotz.h, src/PROPOSAL/PROPOSAL/secondaries/parametrization/photopairproduction/PhotoPairProductionTsai.h, src/PROPOSAL/PROPOSAL/secondaries/parametrization/photopairproduction/SauterSampling.h, src/pyPROPOSAL/detail/secondaries.cxx
When investigating the two photopair angle sampling methods we currently use (Tsai and ForwardPeaked), I saw that the median value differs by quite a lot:
I looked in the EGS5 manual, where a very simple sampling method has been suggested with formula (2.157).
I implemented this method as a test, and to my surprise, it reproduces the current implementation by Tsai quite well:
Note that both plots are created for an interaction of a 1e4 MeV Photon with a nitrogen atom.
However, the Sauter implementation is almost as quick as the crude EGS4 approximation, which itself is two order of magnitudes quicker than the Tsai sampling.
I am a bit surprised that the Sauter sampling methods reproduces the results by Tsai that well, especially since in the EGS5 manual, the method is called "a crude …
=> Add new sampling method for photopair

.github/workflows/cpp.yml
With the update in #365, tests were not executed anymore because they weren't cached.
This PR caches the folder where tests are saved, so they are actually run.
=> Fix execution of tests in new CI

src/PROPOSAL/detail/PROPOSAL/scattering/multiple_scattering/Moliere.cxx
When `MoliereInterpol` creates the interpolation tables, it evaluates the function at negative x. 
This becomes a problem if floating point exceptions are caught. This simple patch protects the function from evaluation of the square root at negative x.
=> Protect Moliere evaluation from negative x

src/PROPOSAL/detail/PROPOSAL/decay/LeptonicDecayChannel.cxx
This has been an issue observed in icetray simulations on specific MacOS machines, and since the decay code is still identical, this might also become a problem for PROPOSAL 7.
=> Avoid possible nan in LeptonicDecayChannel::DecayRate.
